"""initial schema all models

Revision ID: 8f01e7bf36ce
Revises: 
Create Date: 2026-09-09 14:56:37.438083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f01e7bf36ce'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True, comment='被操作模型（如 boq_item）'),
    sa.Column('res_id', sa.Integer(), nullable=True, comment='记录 ID（软引用，不建外键）'),
    sa.Column('action', sa.String(length=30), nullable=False, comment='动作（create/write/soft_delete/restore/import/export/hard_delete）'),
    sa.Column('field_name', sa.String(length=100), nullable=True, comment='变更字段（write 时逐字段记）'),
    sa.Column('old_value', sa.Text(), nullable=True, comment='变更前（截断 512）'),
    sa.Column('new_value', sa.Text(), nullable=True, comment='变更后（截断 512）'),
    sa.Column('operator', sa.String(length=100), nullable=True, comment='操作人（OA 用户名，审计四元组之一）'),
    sa.Column('reason', sa.Text(), nullable=True, comment='变更原因（B 类字段变更必须人工填写，审计四元组之一）'),
    sa.Column('trace_id', sa.String(length=64), nullable=True, comment='追踪 ID（请求级，审计四元组之一）'),
    sa.Column('timestamp', sa.DateTime(), nullable=False, comment='时间（审计四元组之一）'),
    sa.Column('batch_id', sa.Integer(), nullable=True, comment='关联批次 ID（软引用，不建外键）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_model'), 'audit_log', ['model'], unique=False)
    op.create_index('ix_audit_log_model_res', 'audit_log', ['model', 'res_id'], unique=False)
    op.create_table('import_batch',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True, comment='批次名（默认：源文件名 + 时间戳）'),
    sa.Column('source_file', sa.String(), nullable=True, comment='来源文件名'),
    sa.Column('file_hash', sa.String(length=64), nullable=True, comment='文件校验和 SHA256（幂等键）'),
    sa.Column('row_count', sa.Integer(), nullable=False, comment='解析总行数'),
    sa.Column('imported_count', sa.Integer(), nullable=False, comment='入库行数'),
    sa.Column('skipped_count', sa.Integer(), nullable=False, comment='跳过行数'),
    sa.Column('anomaly_count', sa.Integer(), nullable=False, comment='异常行数'),
    sa.Column('imported_at', sa.DateTime(), nullable=False, comment='入库时间'),
    sa.Column('province', sa.String(), nullable=True, comment='地区（批次级，行级可覆盖）'),
    sa.Column('price_period', sa.Date(), nullable=True, comment='价格期（批次级，行级可覆盖，存当月 1 日）'),
    sa.Column('operator', sa.String(), nullable=True, comment='操作人（OA 用户名，用户删除不连带批次）'),
    sa.Column('archive_path', sa.String(), nullable=True, comment='归档相对路径（为空即归档失败，属异常批次）'),
    sa.Column('source_path', sa.String(), nullable=True, comment='原始路径（仅供人读参考，文件可能已被移动）'),
    sa.Column('checksum_count', sa.Integer(), nullable=True, comment='校验行数（入库行数校验，仅数 active=True）'),
    sa.Column('checksum_total', sa.Numeric(precision=16, scale=2), nullable=True, comment='校验合价（sum(total_num)，Decimal 累加后取 2 位）'),
    sa.Column('checksum_hash', sa.String(length=64), nullable=True, comment='校验哈希（按 sequence 升序拼接关键字段后 SHA256）'),
    sa.Column('data_source_type', sa.String(length=20), nullable=False, comment='数据性质（批次级，行级可覆盖。行级模型强制 required）'),
    sa.Column('active', sa.Boolean(), nullable=False, comment='有效（软删除标记）'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='软删除时间（进入回收站的时间，30 天硬删窗口起点）'),
    sa.Column('biz_id', sa.String(length=36), nullable=False, comment='稳定业务 ID（UUID4）。create 自动生成、不可变。'),
    sa.Column('create_date', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('write_date', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('biz_id')
    )
    op.create_index(op.f('ix_import_batch_active'), 'import_batch', ['active'], unique=False)
    op.create_index(op.f('ix_import_batch_file_hash'), 'import_batch', ['file_hash'], unique=False)
    op.create_table('match_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('boq_item_id', sa.Integer(), nullable=False, comment='清单项 ID'),
    sa.Column('candidates', sa.JSON(), nullable=False, comment='Top-N 候选列表（JSON）'),
    sa.Column('top1_score', sa.Integer(), nullable=True, comment='Top-1 分数（用于快速筛选高置信）'),
    sa.Column('cache_version', sa.String(length=32), nullable=False, comment='缓存版本（字典变更后失效）'),
    sa.Column('computed_at', sa.DateTime(), nullable=False, comment='计算时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_match_cache_boq_item', 'match_cache', ['boq_item_id'], unique=False)
    op.create_index(op.f('ix_match_cache_boq_item_id'), 'match_cache', ['boq_item_id'], unique=False)
    op.create_index('ix_match_cache_top1_score', 'match_cache', ['top1_score'], unique=False)
    op.create_table('material_dict',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False, comment='层级（l1 大类 / l2 系列 / l3 规格集合）'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父级（树形三级。有子级/被引用时禁止删除，须先删叶子）'),
    sa.Column('name', sa.String(), nullable=False, comment='名称（L3 为规格集合名）'),
    sa.Column('cat_l1', sa.String(), nullable=True, comment='一级分类（冗余平铺，由父链自动写入）'),
    sa.Column('cat_l2', sa.String(), nullable=True, comment='二级分类（冗余平铺，由父链自动写入）'),
    sa.Column('cat_l3', sa.String(), nullable=True, comment='三级分类（冗余平铺，由父链自动写入）'),
    sa.Column('synonyms', sa.JSON(), nullable=True, comment='同义词（物料业务同义词，如 电缆/电力电缆/YJV）'),
    sa.Column('spec_whitelist', sa.JSON(), nullable=True, comment='规格白名单（合法规格取值集合，用于归一/校验）'),
    sa.Column('note', sa.Text(), nullable=True, comment='备注'),
    sa.Column('biz_id', sa.String(length=36), nullable=False, comment='稳定业务 ID（UUID4）。create 自动生成、不可变。'),
    sa.Column('create_date', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('write_date', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['parent_id'], ['material_dict.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('biz_id')
    )
    op.create_index(op.f('ix_material_dict_name'), 'material_dict', ['name'], unique=False)
    op.create_index(op.f('ix_material_dict_parent_id'), 'material_dict', ['parent_id'], unique=False)
    op.create_table('tag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False, comment='标签名称'),
    sa.Column('color', sa.String(length=16), nullable=False, comment='标签颜色'),
    sa.Column('description', sa.String(length=256), nullable=True, comment='标签描述'),
    sa.Column('created_by', sa.String(length=128), nullable=False, comment='创建者用户名'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('boq_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=False, comment='溯源批次。RESTRICT：批次物理删除时若有明细行将被 DB 拒绝（防误删）；批次的「失效/删除」统一走软删 active=False，明细行自然保留。'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父级（层级折叠）'),
    sa.Column('depth', sa.Integer(), nullable=True, comment='层级深度'),
    sa.Column('sequence', sa.Integer(), nullable=False, comment='行序（导入时 = Excel 物理行号，保证还原原始顺序）'),
    sa.Column('project_name', sa.String(), nullable=True, comment='工程名称'),
    sa.Column('sub_division', sa.String(), nullable=True, comment='子分部'),
    sa.Column('province', sa.String(), nullable=True, comment='地区'),
    sa.Column('price_period', sa.Date(), nullable=True, comment='价格期（存储约定：一律存当月 1 日，如 2026-03-01）'),
    sa.Column('ordinal', sa.String(), nullable=True, comment='清单内行号'),
    sa.Column('item_code', sa.String(), nullable=True, comment='项目编码（国标 9 位 / 12 位，入库保留完整编码用于溯源，匹配时取前 9 位）'),
    sa.Column('item_code_raw', sa.String(), nullable=True, comment='编码原始值（始终保留单元格原始字符串，含前导 0 / 异常长度）'),
    sa.Column('item_code_version', sa.String(length=20), nullable=True, comment='清单版本（2013/2024/unknown）'),
    sa.Column('item_name', sa.String(), nullable=False, comment='项目名称'),
    sa.Column('item_feature', sa.Text(), nullable=True, comment='项目特征描述'),
    sa.Column('unit', sa.String(), nullable=True, comment='计量单位'),
    sa.Column('unit_std', sa.String(), nullable=True, comment='归一化单位（A 类可重建，导入期经 data.unit_normalize 写入）'),
    sa.Column('quantity', sa.String(), nullable=True, comment='工程量（文本保真）'),
    sa.Column('quantity_num', sa.Numeric(precision=16, scale=6), nullable=True, comment='工程量（数值）'),
    sa.Column('unit_rate', sa.String(), nullable=True, comment='综合单价（文本保真）'),
    sa.Column('unit_rate_num', sa.Numeric(precision=16, scale=6), nullable=True, comment='综合单价（数值）'),
    sa.Column('total', sa.String(), nullable=True, comment='合价（文本保真）'),
    sa.Column('total_num', sa.Numeric(precision=16, scale=6), nullable=True, comment='合价（数值）'),
    sa.Column('provisional_sum', sa.String(), nullable=True, comment='暂列金额/暂估价（文本保真）'),
    sa.Column('provisional_sum_num', sa.Numeric(precision=16, scale=6), nullable=True, comment='暂列金额/暂估价（数值）'),
    sa.Column('std_name', sa.String(), nullable=True, comment='标准化项目名称（B 类，禁静默覆盖）'),
    sa.Column('std_spec', sa.String(), nullable=True, comment='标准化规格（B 类，禁静默覆盖）'),
    sa.Column('material_dict_id', sa.Integer(), nullable=True, comment='物料分类（B 类，三级材料分类字典关联，仅人工确认后写入；字典项删改时明细行保留）'),
    sa.Column('data_source_type', sa.String(length=20), nullable=False, comment='数据性质（completed/control_price/bid_price/pending_review/info_price）。nullable=False 无默认值：create 必须显式带值，防绕过向导把待审/控制价混入历史均价。统计默认域只取 completed；pending_review 永不进历史均价。'),
    sa.Column('match_key', sa.String(), nullable=True, comment='同类项聚合键（M1.2 compute：优先级 dict > std > Z前缀 > 有效国标码 > raw，带清单版本维度）'),
    sa.Column('aggregate_id', sa.String(), nullable=True, comment='跨行聚合身份（material_dict_id 存在时 = dict:<id>，否则 = match_key。M3 单价分析 / M4 成本库迁移一律按此字段聚合）'),
    sa.Column('match_key_source', sa.String(length=20), nullable=True, comment='聚合键来源（dict/std/code/raw），让统计口径可解释'),
    sa.Column('anomaly_flag', sa.String(length=20), nullable=False, comment='异常标记（normal/warning/error，B 类）'),
    sa.Column('anomaly_reason', sa.Text(), nullable=True, comment='异常原因（B 类）'),
    sa.Column('active', sa.Boolean(), nullable=False, comment='有效（软删除标记）'),
    sa.Column('orphaned', sa.Boolean(), nullable=False, comment='孤儿行（仅由重导产生：active=False + orphaned=True 进待确认/回收站，与 anomaly_flag 正交）'),
    sa.Column('source_path', sa.String(), nullable=True, comment='来源路径（仅人读参考，正式溯源走批次 archive_path）'),
    sa.Column('source_sheet', sa.String(), nullable=True, comment='来源 Sheet'),
    sa.Column('classification', sa.JSON(), nullable=True, comment='编码解析（专业/分部）'),
    sa.Column('extra', sa.JSON(), nullable=True, comment='未映射列（原样保留）'),
    sa.Column('version', sa.Integer(), nullable=False, comment='版本'),
    sa.Column('biz_id', sa.String(length=36), nullable=False, comment='稳定业务 ID（UUID4）。create 自动生成、不可变。'),
    sa.Column('create_date', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('write_date', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batch.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['material_dict_id'], ['material_dict.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['boq_item.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('biz_id')
    )
    op.create_index(op.f('ix_boq_item_active'), 'boq_item', ['active'], unique=False)
    op.create_index(op.f('ix_boq_item_aggregate_id'), 'boq_item', ['aggregate_id'], unique=False)
    op.create_index(op.f('ix_boq_item_anomaly_flag'), 'boq_item', ['anomaly_flag'], unique=False)
    op.create_index('ix_boq_item_batch_seq', 'boq_item', ['import_batch_id', 'sequence'], unique=False)
    op.create_index('ix_boq_item_code_unit', 'boq_item', ['item_code', 'unit'], unique=False)
    op.create_index(op.f('ix_boq_item_data_source_type'), 'boq_item', ['data_source_type'], unique=False)
    op.create_index(op.f('ix_boq_item_import_batch_id'), 'boq_item', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_boq_item_item_code'), 'boq_item', ['item_code'], unique=False)
    op.create_index(op.f('ix_boq_item_item_code_version'), 'boq_item', ['item_code_version'], unique=False)
    op.create_index(op.f('ix_boq_item_item_name'), 'boq_item', ['item_name'], unique=False)
    op.create_index(op.f('ix_boq_item_match_key'), 'boq_item', ['match_key'], unique=False)
    op.create_index(op.f('ix_boq_item_material_dict_id'), 'boq_item', ['material_dict_id'], unique=False)
    op.create_index(op.f('ix_boq_item_parent_id'), 'boq_item', ['parent_id'], unique=False)
    op.create_index(op.f('ix_boq_item_project_name'), 'boq_item', ['project_name'], unique=False)
    op.create_index('ix_boq_item_project_seq', 'boq_item', ['project_name', 'sequence'], unique=False)
    op.create_index('ix_boq_item_province_period', 'boq_item', ['province', 'price_period'], unique=False)
    op.create_index(op.f('ix_boq_item_unit_std'), 'boq_item', ['unit_std'], unique=False)
    op.create_table('cost_catalog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_key', sa.String(length=256), nullable=False, comment='聚合键，与 boq_item.match_key 一致；UNIQUE 保证每条 match_key 一条记录'),
    sa.Column('match_key_source', sa.String(length=32), nullable=False, comment='聚合键来源：dict/std/code/raw，与 boq_item.match_key_source 一致'),
    sa.Column('std_name', sa.String(length=512), nullable=False, comment='标准化名称（B 类不可重建字段，迁移后不开放直接编辑）'),
    sa.Column('std_spec', sa.String(length=512), nullable=False, comment='标准化规格（B 类不可重建字段）'),
    sa.Column('material_dict_id', sa.Integer(), nullable=True, comment='物料分类关联（B 类；SET NULL：字典项删除时成本库保留，仅断开关联）'),
    sa.Column('unit_std', sa.String(length=32), nullable=False, comment='归一化单位'),
    sa.Column('avg_rate', sa.Numeric(precision=16, scale=6), nullable=True, comment='历史均价（completed 行 unit_rate_num 的算术平均）'),
    sa.Column('min_rate', sa.Numeric(precision=16, scale=6), nullable=True, comment='历史最低价'),
    sa.Column('max_rate', sa.Numeric(precision=16, scale=6), nullable=True, comment='历史最高价'),
    sa.Column('sample_count', sa.Integer(), nullable=True, comment='参与统计的 completed 行数（unit_rate_num 非空）'),
    sa.Column('latest_price', sa.Numeric(precision=16, scale=6), nullable=True, comment='最新一条 completed 行的单价（按 price_period 降序取首条）'),
    sa.Column('latest_period', sa.Date(), nullable=True, comment='最新价格期'),
    sa.Column('latest_source', sa.String(length=512), nullable=True, comment='最新记录来源（工程名 project_name）'),
    sa.Column('embedding_version', sa.Integer(), nullable=True, comment='embedding 同步版本计数器；每次重建 LanceDB 索引 +1，用于检测漂移'),
    sa.Column('vector_sync_pending', sa.Boolean(), nullable=False, comment='PG 已更新但 LanceDB 向量未同步标记（写 PG 成功、向量失败时的补偿位点）'),
    sa.Column('migration_batch_id', sa.Integer(), nullable=True, comment='迁移批次溯源（最近一次迁移该记录的 import_batch.id）'),
    sa.Column('active', sa.Boolean(), nullable=False, comment='软删除标记；cost_catalog 不物理删除，刷新时重建'),
    sa.Column('biz_id', sa.String(length=36), nullable=False, comment='稳定业务 ID（UUID4）。create 自动生成、不可变。'),
    sa.Column('create_date', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('write_date', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['material_dict_id'], ['material_dict.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['migration_batch_id'], ['import_batch.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('biz_id')
    )
    op.create_index(op.f('ix_cost_catalog_active'), 'cost_catalog', ['active'], unique=False)
    op.create_index(op.f('ix_cost_catalog_match_key'), 'cost_catalog', ['match_key'], unique=True)
    op.create_index(op.f('ix_cost_catalog_material_dict_id'), 'cost_catalog', ['material_dict_id'], unique=False)
    op.create_index(op.f('ix_cost_catalog_migration_batch_id'), 'cost_catalog', ['migration_batch_id'], unique=False)
    op.create_index('ix_cost_catalog_std_name', 'cost_catalog', ['std_name'], unique=False)
    op.create_index('ix_cost_catalog_unit_std', 'cost_catalog', ['unit_std'], unique=False)
    op.create_table('item_tag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False, comment='标签 ID'),
    sa.Column('boq_item_id', sa.Integer(), nullable=False, comment='清单项 ID'),
    sa.Column('username', sa.String(length=128), nullable=False, comment='打标签的用户'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='打标签时间'),
    sa.ForeignKeyConstraint(['boq_item_id'], ['boq_item.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag_id', 'boq_item_id', 'username', name='uq_item_tag_user')
    )
    op.create_index('ix_item_tag_tag_item', 'item_tag', ['tag_id', 'boq_item_id'], unique=False)
    op.create_index(op.f('ix_item_tag_username'), 'item_tag', ['username'], unique=False)
    op.create_table('user_favorite',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False, comment='用户名'),
    sa.Column('boq_item_id', sa.Integer(), nullable=False, comment='收藏的清单项 ID'),
    sa.Column('note', sa.String(length=500), nullable=True, comment='收藏备注'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='收藏时间'),
    sa.ForeignKeyConstraint(['boq_item_id'], ['boq_item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', 'boq_item_id', name='uq_user_favorite_item')
    )
    op.create_index(op.f('ix_user_favorite_username'), 'user_favorite', ['username'], unique=False)
    op.create_index('ix_user_favorite_username_created', 'user_favorite', ['username', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_favorite_username_created', table_name='user_favorite')
    op.drop_index(op.f('ix_user_favorite_username'), table_name='user_favorite')
    op.drop_table('user_favorite')
    op.drop_index(op.f('ix_item_tag_username'), table_name='item_tag')
    op.drop_index('ix_item_tag_tag_item', table_name='item_tag')
    op.drop_table('item_tag')
    op.drop_index('ix_cost_catalog_unit_std', table_name='cost_catalog')
    op.drop_index('ix_cost_catalog_std_name', table_name='cost_catalog')
    op.drop_index(op.f('ix_cost_catalog_migration_batch_id'), table_name='cost_catalog')
    op.drop_index(op.f('ix_cost_catalog_material_dict_id'), table_name='cost_catalog')
    op.drop_index(op.f('ix_cost_catalog_match_key'), table_name='cost_catalog')
    op.drop_index(op.f('ix_cost_catalog_active'), table_name='cost_catalog')
    op.drop_table('cost_catalog')
    op.drop_index(op.f('ix_boq_item_unit_std'), table_name='boq_item')
    op.drop_index('ix_boq_item_province_period', table_name='boq_item')
    op.drop_index('ix_boq_item_project_seq', table_name='boq_item')
    op.drop_index(op.f('ix_boq_item_project_name'), table_name='boq_item')
    op.drop_index(op.f('ix_boq_item_parent_id'), table_name='boq_item')
    op.drop_index(op.f('ix_boq_item_material_dict_id'), table_name='boq_item')
    op.drop_index(op.f('ix_boq_item_match_key'), table_name='boq_item')
    op.drop_index(op.f('ix_boq_item_item_name'), table_name='boq_item')
    op.drop_index(op.f('ix_boq_item_item_code_version'), table_name='boq_item')
    op.drop_index(op.f('ix_boq_item_item_code'), table_name='boq_item')
    op.drop_index(op.f('ix_boq_item_import_batch_id'), table_name='boq_item')
    op.drop_index(op.f('ix_boq_item_data_source_type'), table_name='boq_item')
    op.drop_index('ix_boq_item_code_unit', table_name='boq_item')
    op.drop_index('ix_boq_item_batch_seq', table_name='boq_item')
    op.drop_index(op.f('ix_boq_item_anomaly_flag'), table_name='boq_item')
    op.drop_index(op.f('ix_boq_item_aggregate_id'), table_name='boq_item')
    op.drop_index(op.f('ix_boq_item_active'), table_name='boq_item')
    op.drop_table('boq_item')
    op.drop_table('tag')
    op.drop_index(op.f('ix_material_dict_parent_id'), table_name='material_dict')
    op.drop_index(op.f('ix_material_dict_name'), table_name='material_dict')
    op.drop_table('material_dict')
    op.drop_index('ix_match_cache_top1_score', table_name='match_cache')
    op.drop_index(op.f('ix_match_cache_boq_item_id'), table_name='match_cache')
    op.drop_index('ix_match_cache_boq_item', table_name='match_cache')
    op.drop_table('match_cache')
    op.drop_index(op.f('ix_import_batch_file_hash'), table_name='import_batch')
    op.drop_index(op.f('ix_import_batch_active'), table_name='import_batch')
    op.drop_table('import_batch')
    op.drop_index('ix_audit_log_model_res', table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_model'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
